### ISSUE TITLE
[TRACKER] Features for upcoming release

### ISSUE THREAD

**Issue by MrKevinWeiss** [riot-appstore/PHiLIP#64]
This is a collection of features/fixes/tasks to be implemented for the next release.

- [ ] Update Licenses to SPDX identifiers
- [ ] Fix spelling mistakes #62
- [ ] Add codespell to CI
- [ ] Fix error messages on philip_pal when no connection #56 #57 
- [ ] Add GPIO control for each peripheral pin 60
- [ ] Cleanup and simplify SPI functionality #59 
- [ ] Change readline history to something unique to not interfere with RIOT terminal #58 
- [ ] Add fixes to philip_pal discovered by other *_pal
- [ ] Expose show_pinout command through CLI to connection is not needed #46 
- [ ] Fix trace logging time issue #45 
- [ ] philip_pal documentaiton to sphinx and generate output
- [ ] Evaluate and improve i2c lockup and sda error injection #32
- [ ] Cleanup saved reg to only use what is needed
- [ ] Ensure periodic interrupts can be disabled
- [ ] Add disable bph (everything to input)
- [ ] Use DMA for SPI reg output
- [ ] Add timer for quick time measurements
- [ ] Add qualification for ADC and DAC
- [ ] Incorperate Digilent Analog Discovery 2 to qualifcation process
